services:
  - type: web
    name: resume-score-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    autoDeploy: true
